
apiVersion: v1
kind: Secret
metadata:
  name: cb-ansible-created-user-credential
  namespace: default
type: Opaque
data:
  password: cGFzc3dvcmQ=   # password

---

apiVersion: couchbase.com/v2
kind: CouchbaseUser
metadata:
  name: ansibleuser
  namespace: default
  labels:
    cluster: my-cluster
spec:
  fullName: "Ansible User"
  authDomain: local
  authSecret: cb-ansible-created-user-credential

---

apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
  name: developers
  namespace: default
  labels:
    cluster: my-cluster
spec:
  roles:
  - name: bucket_full_access
    bucket: default


---

apiVersion: couchbase.com/v2
kind: CouchbaseRoleBinding
metadata:
  name: developers
  namespace: default
spec:
  subjects:
  - kind: CouchbaseUser
    name: ansibleuser
  roleRef:
    kind: CouchbaseGroup
    name: developers
