apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
  name: cb-ansible-testa
  namespace: dev
  labels:
    cluster: my-cluster
spec:
  roles:
  - name: bucket_full_access
    bucket: default
